import pandas as pd
import streamlit as st
from pathlib import Path

st.set_page_config(page_title="LinkedIn Growth Solution", layout="wide")
st.title("LinkedIn Growth Solution — Live Dashboard")
st.caption("Auto-generated by Linkedin_Report_Task1.py")

out = Path("out")
if not out.exists():
    st.warning("No outputs found. Run `python Linkedin_Report_Task1.py` once to generate `out/`.")
    st.stop()

def read_csv_safe(path):
    try:
        return pd.read_csv(path)
    except Exception as e:
        st.error(f"Failed to read {path}: {e}")
        return pd.DataFrame()

feat = read_csv_safe(out / "post_features_and_predictions.csv")
icp  = read_csv_safe(out / "post_icp_relevance.csv")
summary = read_csv_safe(out / "summary_ranked.csv")

if not summary.empty:
    st.subheader("Top Posts (ranked)")
    cols = ["post_id","engagement_rate","ctr","predicted_performance_score","icp_relevance_score","url"]
    view_cols = [c for c in cols if c in summary.columns]
    st.dataframe(summary[view_cols].sort_values(
        ["predicted_performance_score","engagement_rate"], ascending=False),
        use_container_width=True
    )

with st.expander("Feature Details", expanded=True):
    if feat.empty:
        st.info("No feature CSV yet.")
    else:
        st.dataframe(feat, use_container_width=True)

with st.expander("ICP Relevance"):
    if icp.empty:
        st.info("No ICP CSV yet.")
    else:
        st.dataframe(icp, use_container_width=True)

st.divider()
st.caption("Tip: rerun the script daily via GitHub Actions (see .github/workflows/daily-report.yml).")